# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3"
services:
  redis-vector-db:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-vector-db
    ports:
      - "6379:6379"
      - "8001:8001"
  dataprep-redis:
    image: opea/dataprep-redis:latest
    container_name: dataprep-redis-server
    ports:
      - "6006:6006"
      - "6007:6007"
      - "6008:6008"
      - "6009:6009"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      INDEX_NAME: ${INDEX_NAME}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LVM_ENDPOINT: ${LVM_ENDPOINT}
    restart: unless-stopped
  llava-server:
    image: opea/llava:latest
    container_name: llava-server
    ports:
      - "8399:8399"
    ipc: host
    runtime: habana
    cap-add: sys_nice
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    restart: unless-stopped
  lvm-service:
    image: opea/lvm:latest
    container_name: lvm-server
    ports:
      - "9399:9399"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LVM_ENDPOINT: ${LVM_ENDPOINT}

networks:
  default:
    driver: bridge
